.TH READPE-NG "1" "November 2025" "objtools 0.1" "User Commands"
.SH NAME
readpe-ng: display information about ELF and PE files.

.SH SYNOPSIS
readpe-ng [\fB\-h\fR|\fB\-\-help\fR]
          [\fB\-v\fR|\fB\-\-version\fR]
          [\fB\-S\fR|\fB\-\-section\-headers\fR]
          [\fB\-V\fR|\fB\-\-version\-info\fR]
          [\fB\-a\fR|\fB\-\-all\fR]
          [\fB\-H\fR|\fB\-\-headers\fR]
          [\fB\-G\fR|\fB\-\-section\-groups\fR]
          [\fB\-D\fR|\fB\-\-dos\-header\fR]
          [\fB\-N\fR|\fB\-\-nt-header\fR]
          [\fB\-R\fR|\fB\-\-relocs\fR]
          [\fB\-E\fR|\fB\-\-eat\fR]
          [\fB\-I\fR|\fB\-\-iat\fR]
          [\fB\-m\fR|\fB\-\-runtime\fR]
          [\fB\-g\fR|\fB\-\-debug\fR]
          [\fB\-f\fR|\fB\-\-config\fR]
          [\fB\-o\fR|\fB\-\-resource\fR]
          [\fB\-x\fR <number or name>|\fB\-\-hex\-dump=\fR<number or name>]
          [\fB\-c\fR <number or name>|\fB\-\-code\-dump=\fR<number or name>]
          [\fB\-s\fR <number or name>|\fB\-\-string\-dump=\fR<number or name>]
          [\fB\-u\fR <number or name>|\fB\-\-unicode\-dump=\fR<number or name>]
          [\fB\-r\fR <number or name>|\fB\-\-relocated\-dump=\fR<number or name>]
          [\fB\-t\fR <options>|\fB\-\-script=\fR<options>]
          [\fB\-i\fR|\fB\-\-info\fR]
          [\fB\-X\fR|\fB\-\-hash\fR]
          [\fB\-e\fR|\fB\-\-entropy\fR]
          [\fB\-M\fR <options>|\fB\-\-disassembler\-options=\fR<options>]

.SH DESCRIPTION
\fBreadpe-ng\fR displays information about one or more PE format object files. The options control what particular information to display.

\fIpefile...\fR are the object files to be examined. 32-bit and 64-bit PE files are supported.

.SH OPTIONS
.IP "\fB\-h\fR" 4
.IX Item "-h"
.PD 0
.IP "\fB\-\-help\fR" 4
.IX Item "--help"
.PD
Print a summary of the options to readpe-ng and exit.
.IP "\fB\-v\fR" 4
.IX Item "-v"
.PD 0
.IP "\fB\-\-version\fR" 4
.IX Item "--version"
.PD
Print the version number of readpe-ng and exit.
.IP "\fB\-S\fR" 4
.IX Item "-S"
.PD 0
.IP "\fB\-\-section\-headers\fR" 4
.IX Item "--section\-headers"
.PD
Displays the information contained in the file's section headers.
.IP "\fB\-V\fR" 4
.IX Item "-V"
.PD 0
.IP "\fB\-\-version\-info\fR" 4
.IX Item "--version\-info"
.PD
Displays the information contained in the file's version section.
.IP "\fB\-a\fR" 4
.IX Item "-a"
.PD 0
.IP "\fB\-\-all\fR" 4
.IX Item "--all"
Equivalent to specifying: \fB\-\-section\-headers\fR, \fB\-\-section\-groups\fR, \fB\-\-dos\-header\fR, \fB\-\-nt\-header\fR, \fB\-\-relocs\fR, \fB\-\-eat\fR, \fB\-\-iat\fR and \fB\-\-runtime\fR.
.IP "\fB\-H\fR" 4
.IX Item "-H"
.PD 0
.IP "\fB\-\-headers\fR" 4
.IX Item "--headers"
Displays the information contained in the file's headers.
Equivalent to specifying: \fB\-\-section\-headers\fR, \fB\-\-dos\-header\fR, and \fB\-\-nt\-header\fR.

  -G
  --section-groups
    Displays the information contained in the file's version section.

  -D
  --dos-header
    Displays the contents of the DOS header.

  -N
  --nt-header
    Displays the contents of the NT header.

  -R
  --relocs
    Displays the contents of the file's relocation section.

  -E
  --eat
    Displays the contents of the Export Address Table section.

  -I
  --iat
    Displays the contents of the Import Address Table section.

  -m
  --runtime
    Displays the contents of the runtine section.

  -g
  --debug
    Displays the contents of the debug information section.

  -f
  --config
    Displays the contents of the configuration section.

  -o
  --resource
    Displays the contents of the resource information section.
.IP "\fB\-x <number or name>\fR" 4
.IX Item "-x <number or name>"
.PD 0
.IP "\fB\-\-hex\-dump=<number or name>\fR" 4
.IX Item "--hex-dump=<number or name>"
.PD
Displays the contents of the indicated section as a hexadecimal bytes.
.IP "\fB\-c <number or name>\fR" 4
.IX Item "-c <number or name>"
.PD 0
.IP "\fB\-\-code\-dump=<number or name>\fR" 4
.IX Item "--code-dump=<number or name>"
.PD
Displays the contents of the indicated section as C Language Shell Code.
.IP "\fB\-s <number or name>\fR" 4
.IX Item "-s <number or name>"
.PD 0
.IP "\fB\-\-string\-dump=<number or name>\fR" 4
.IX Item "--string-dump=<number or name>"
.PD
Displays the contents of the indicated section as printable strings.
.IP "\fB\-u <number or name>\fR" 4
.IX Item "-u <number or name>"
.PD 0
.IP "\fB\-\-unicode\-dump=<number or name>\fR" 4
.IX Item "--unicode-dump=<number or name>"
.PD
Displays the contents of the indicated section as printable strings.
.IP "\fB\-r <number or name>\fR" 4
.IX Item "-r <number or name>"
.PD 0
.IP "\fB\-\-relocated\-dump=<number or name>\fR" 4
.IX Item "--relocated-dump=<number or name>"
.PD
Displays the contents of the indicated section as a hexadecimal bytes.

  -t
  --script
    Generate simple scripts to modify any section to reverse obfuscation.

  -i
  --info
    Equivalent to specifying: --hash --entropy

  -X
  --hash
    Calculates and displays the SHA-256 hash.

  -e
  --entropy
    Displays the entropy of the object.

.IP "\fB\-M <options>\fR" 4
.IX Item "-M <options>"
.PD 0
.IP "\fB\-\-disassembler\-options=<options>\fR" 4
.IX Item "--disassembler-options=<options>"
.PD
Pass target specific information to the disassembler.
.RS 4
.ie n .IP """att""" 4
.IX Item "att"
.PD
Select the AT&T syntax mode.
.ie n .IP """intel""" 4
.IX Item "intel"
.PD
Select the Intel syntax mode.
.ie n .IP """x86-64""" 4
.IX Item "x86-64"
.PD 0
.ie n .IP """i386""" 4
.IX Item "i386"
.ie n .IP """i8086""" 4
.IX Item "i8086"
.PD
Select disassembly for the given architecture.
.ie n .IP """amd64""" 4
.IX Item "amd64"
.PD 0
.ie n .IP """intel64""" 4
.IX Item "intel64"
.PD
Select between AMD64 ISA and Intel64 ISA.
.ie n .IP """addr16""" 4
.IX Item "addr16"
.PD 0
.ie n .IP """addr32""" 4
.IX Item "addr32"
.ie n .IP """addr64""" 4
.IX Item "addr64"
.ie n .IP """data16""" 4
.IX Item "data16"
.ie n .IP """data32""" 4
.IX Item "data32"
.PD
Specify the default address size and operand size.

.SH SEE ALSO
convert-ng(1), objcopy-ng(1), objdump-ng(1), objdwarf-ng(1), objhash-ng(1), readelf-ng(1), readpe-ng(1)

.SH COPYRIGHT
.IX Header "COPYRIGHT"
MIT License
.PP
Copyright (c) 2025 Kyle Wickens

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
