#ifndef __OPCODE_EXAMINE_RISCV_H_
#define __OPCODE_EXAMINE_RISCV_H_

#define OCINSTRUCTION_LOAD             ((0x01) | OCINSN_OPERAND2)

#define OCINSNRISCV_SIGNED             (OCINSN_S)
#define OCINSNRISCV_UNSIGNED           (OCINSN_N)

#define OCINSTRUCTION_LB               (OCINSTRUCTION_LOAD | OCINSN_8BIT)
#define OCINSTRUCTION_LD               (OCINSTRUCTION_LOAD | OCINSN_64BIT)
#define OCINSTRUCTION_LH               (OCINSTRUCTION_LOAD | OCINSN_16BIT)
#define OCINSTRUCTION_LW               (OCINSTRUCTION_LOAD | OCINSN_32BIT)

#define OCINSTRUCTION_LBU              (OCINSTRUCTION_LB | OCINSNRISCV_UNSIGNED)
#define OCINSTRUCTION_LHU              (OCINSTRUCTION_LH | OCINSNRISCV_UNSIGNED)
#define OCINSTRUCTION_LWU              (OCINSTRUCTION_LW | OCINSN_32BIT | OCINSNRISCV_UNSIGNED)

#endif

