#ifndef __OPCODE_EXAMINE_RISCV_H_
#define __OPCODE_EXAMINE_RISCV_H_

#define OCINSNRISCV_LOAD               ((0x01) | OCINSN_OPERAND2)
#define OCINSNRISCV_STORE              ((0x02) | OCINSN_OPERAND2)

#define OCINSNRISCV_SIGNED             (OCINSN_S)
#define OCINSNRISCV_UNSIGNED           (OCINSN_N)

#define OCINSNRISCV_LB                 (OCINSNRISCV_LOAD | OCINSN_8BIT)
#define OCINSNRISCV_LD                 (OCINSNRISCV_LOAD | OCINSN_64BIT)
#define OCINSNRISCV_LH                 (OCINSNRISCV_LOAD | OCINSN_16BIT)
#define OCINSNRISCV_LW                 (OCINSNRISCV_LOAD | OCINSN_32BIT)

#define OCINSNRISCV_LBU                (OCINSNRISCV_LB | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_LHU                (OCINSNRISCV_LH | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_LWU                (OCINSNRISCV_LW | OCINSN_32BIT | OCINSNRISCV_UNSIGNED)

#define OCINSNRISCV_SB                 (OCINSNRISCV_STORE | OCINSN_8BIT)
#define OCINSNRISCV_SD                 (OCINSNRISCV_STORE | OCINSN_64BIT)
#define OCINSNRISCV_SH                 (OCINSNRISCV_STORE | OCINSN_16BIT)
#define OCINSNRISCV_SW                 (OCINSNRISCV_STORE | OCINSN_32BIT)

#endif

