#ifndef __OPCODE_EXAMINE_RISCV_H_
#define __OPCODE_EXAMINE_RISCV_H_

#define OCINSNRISCV_LOAD               ((0x01) | OCINSN_OPERAND2)
#define OCINSNRISCV_STORE              ((0x02) | OCINSN_OPERAND2)
#define OCINSNRISCV_MOVE               ((0x03) | OCINSN_OPERAND2)
#define OCINSNRISCV_NOP                ((0x04) | OCINSN_OPERAND0)
#define OCINSNRISCV_ADD                ((0x10) | OCINSN_OPERAND3)
#define OCINSNRISCV_AxxPC              ((0x11) | OCINSN_OPERAND2)
#define OCINSNRISCV_DIV                ((0x12) | OCINSN_OPERAND3)
#define OCINSNRISCV_MUL                ((0x13) | OCINSN_OPERAND3)
#define OCINSNRISCV_MULH               ((0x14) | OCINSN_OPERAND3)
#define OCINSNRISCV_REM                ((0x15) | OCINSN_OPERAND3)
#define OCINSNRISCV_SUB                ((0x16) | OCINSN_OPERAND3)
#define OCINSNRISCV_AND                ((0x20) | OCINSN_OPERAND3)
#define OCINSNRISCV_ANDN               ((0x21) | OCINSN_OPERAND3)
#define OCINSNRISCV_BINV               ((0x22) | OCINSN_OPERAND3)
#define OCINSNRISCV_MIN                ((0x23) | OCINSN_OPERAND3)
#define OCINSNRISCV_MAX                ((0x24) | OCINSN_OPERAND3)
#define OCINSNRISCV_NOT                ((0x25) | OCINSN_OPERAND2)
#define OCINSNRISCV_OR                 ((0x26) | OCINSN_OPERAND3)
#define OCINSNRISCV_ORN                ((0x27) | OCINSN_OPERAND3)
#define OCINSNRISCV_ROx                ((0x28) | OCINSN_OPERAND3)
#define OCINSNRISCV_SxA                ((0x29) | OCINSN_OPERAND3)
#define OCINSNRISCV_SxL                ((0x2a) | OCINSN_OPERAND3)
#define OCINSNRISCV_XNOR               ((0x2b) | OCINSN_OPERAND3)
#define OCINSNRISCV_XNORN              ((0x2c) | OCINSN_OPERAND3)
#define OCINSNRISCV_XOR                ((0x2d) | OCINSN_OPERAND3)
#define OCINSNRISCV_XORN               ((0x2e) | OCINSN_OPERAND3)

#define OCINSNRISCV_SEXT               ((0x50) | OCINSN_OPERAND2)
#define OCINSNRISCV_ZEXT               ((0x51) | OCINSN_OPERAND2)

#define OCINSNRISCV_Jxx                ((0x60) | OCINSN_OPERAND1)
#define OCINSNRISCV_Bxx                ((0x61) | OCINSN_OPERAND3)

#define OCINSNRISCV_LINK               U64MASK(19)
#define OCINSNRISCV_REGISTER           U64MASK(20)
#define OCINSNRISCV_IMMEDIATE          U64MASK(21)
#define OCINSNRISCV_UPPER              U64MASK(22)

#define OCINSNRISCV_SIGNED             (OCINSN_S)
#define OCINSNRISCV_UNSIGNED           (OCINSN_N)
#define OCINSNRISCV_ZERO               (OCINSN_Z)

#define OCINSNRISCV_EQ                 (OCINSN_E)
#define OCINSNRISCV_EQZ                (OCINSN_E | OCINSN_Z)
#define OCINSNRISCV_GE                 (OCINSN_GE)
#define OCINSNRISCV_GEZ                (OCINSN_GE | OCINSN_Z)
#define OCINSNRISCV_GT                 (OCINSN_G)
#define OCINSNRISCV_GTZ                (OCINSN_G | OCINSN_Z)
#define OCINSNRISCV_LE                 (OCINSN_LE)
#define OCINSNRISCV_LEZ                (OCINSN_LE | OCINSN_Z)
#define OCINSNRISCV_LT                 (OCINSN_L)
#define OCINSNRISCV_LTZ                (OCINSN_L | OCINSN_Z)
#define OCINSNRISCV_NE                 (OCINSN_NE)
#define OCINSNRISCV_NEZ                (OCINSN_NE | OCINSN_Z)

#define OCINSNRISCV_LB                 (OCINSNRISCV_LOAD | OCINSN_8BIT)
#define OCINSNRISCV_LD                 (OCINSNRISCV_LOAD | OCINSN_64BIT)
#define OCINSNRISCV_LH                 (OCINSNRISCV_LOAD | OCINSN_16BIT)
#define OCINSNRISCV_LW                 (OCINSNRISCV_LOAD | OCINSN_32BIT)

#define OCINSNRISCV_LBU                (OCINSNRISCV_LB | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_LHU                (OCINSNRISCV_LH | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_LWU                (OCINSNRISCV_LW | OCINSN_32BIT | OCINSNRISCV_UNSIGNED)

#define OCINSNRISCV_LI                 (OCINSNRISCV_LOAD | OCINSNRISCV_UPPER)
#define OCINSNRISCV_LUI                (OCINSNRISCV_LI | OCINSNRISCV_IMMEDIATE)

#define OCINSNRISCV_SB                 (OCINSNRISCV_STORE | OCINSN_8BIT)
#define OCINSNRISCV_SD                 (OCINSNRISCV_STORE | OCINSN_64BIT)
#define OCINSNRISCV_SH                 (OCINSNRISCV_STORE | OCINSN_16BIT)
#define OCINSNRISCV_SW                 (OCINSNRISCV_STORE | OCINSN_32BIT)

#define OCINSNRISCV_ADDB               (OCINSNRISCV_ADD | OCINSN_8BIT)
#define OCINSNRISCV_ADDH               (OCINSNRISCV_ADD | OCINSN_16BIT)
#define OCINSNRISCV_ADDW               (OCINSNRISCV_ADD | OCINSN_32BIT)

#define OCINSNRISCV_ADDI               (OCINSNRISCV_ADD | OCINSNRISCV_IMMEDIATE)
#define OCINSNRISCV_ADDIB              (OCINSNRISCV_ADDI | OCINSN_8BIT)
#define OCINSNRISCV_ADDIH              (OCINSNRISCV_ADDI | OCINSN_16BIT)
#define OCINSNRISCV_ADDIW              (OCINSNRISCV_ADDI | OCINSN_32BIT)

#define OCINSNRISCV_AUIPC              (OCINSNRISCV_AxxPC | OCINSNRISCV_IMMEDIATE | OCINSNRISCV_UPPER)

#define OCINSNRISCV_DIVU               (OCINSNRISCV_DIV | OCINSNRISCV_UNSIGNED)

#define OCINSNRISCV_MULW               (OCINSNRISCV_MUL | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_MULHU              (OCINSNRISCV_MULH | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_MULHSU             (OCINSNRISCV_MULH | OCINSNRISCV_UNSIGNED | OCINSNRISCV_SIGNED)

#define OCINSNRISCV_REMU               (OCINSNRISCV_REM | OCINSNRISCV_UNSIGNED)

#define OCINSNRISCV_SUBB               (OCINSNRISCV_SUB | OCINSN_8BIT)
#define OCINSNRISCV_SUBH               (OCINSNRISCV_SUB | OCINSN_16BIT)
#define OCINSNRISCV_SUBW               (OCINSNRISCV_SUB | OCINSN_32BIT)

#define OCINSNRISCV_ANDI               (OCINSNRISCV_AND | OCINSNRISCV_IMMEDIATE)

#define OCINSNRISCV_BINVI              (OCINSNRISCV_BINV | OCINSNRISCV_IMMEDIATE)

#define OCINSNRISCV_MINU               (OCINSNRISCV_MIN | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_MAXU               (OCINSNRISCV_MAX | OCINSNRISCV_UNSIGNED)

#define OCINSNRISCV_ORI                (OCINSNRISCV_OR | OCINSNRISCV_IMMEDIATE)

#define OCINSNRISCV_ROL                (OCINSNRISCV_ROx | OCINSN_LT)
#define OCINSNRISCV_ROLI               (OCINSNRISCV_ROL | OCINSNRISCV_IMMEDIATE)
#define OCINSNRISCV_ROLW               (OCINSNRISCV_ROL | OCINSN_32BIT)
#define OCINSNRISCV_ROLIW              (OCINSNRISCV_ROLI | OCINSN_32BIT)
#define OCINSNRISCV_ROR                (OCINSNRISCV_ROx | OCINSN_RT)
#define OCINSNRISCV_RORI               (OCINSNRISCV_ROR | OCINSNRISCV_IMMEDIATE)
#define OCINSNRISCV_RORW               (OCINSNRISCV_ROR | OCINSN_32BIT)
#define OCINSNRISCV_RORIW              (OCINSNRISCV_RORI | OCINSN_32BIT)

#define OCINSNRISCV_SLA                (OCINSNRISCV_SxA | OCINSN_LT)
#define OCINSNRISCV_SLAI               (OCINSNRISCV_SLA | OCINSNRISCV_IMMEDIATE)
#define OCINSNRISCV_SLAW               (OCINSNRISCV_SLA | OCINSN_32BIT)
#define OCINSNRISCV_SLAIW              (OCINSNRISCV_SLAI | OCINSN_32BIT)
#define OCINSNRISCV_SRA                (OCINSNRISCV_SxA | OCINSN_RT)
#define OCINSNRISCV_SRAI               (OCINSNRISCV_SRA | OCINSNRISCV_IMMEDIATE)
#define OCINSNRISCV_SRAW               (OCINSNRISCV_SRA | OCINSN_32BIT)
#define OCINSNRISCV_SRAIW              (OCINSNRISCV_SRAI | OCINSN_32BIT)

#define OCINSNRISCV_SLL                (OCINSNRISCV_SxL | OCINSN_LT)
#define OCINSNRISCV_SLLI               (OCINSNRISCV_SLL | OCINSNRISCV_IMMEDIATE)
#define OCINSNRISCV_SLLW               (OCINSNRISCV_SLL | OCINSN_32BIT)
#define OCINSNRISCV_SLLIW              (OCINSNRISCV_SLLI | OCINSN_32BIT)
#define OCINSNRISCV_SRL                (OCINSNRISCV_SxL | OCINSN_RT)
#define OCINSNRISCV_SRLI               (OCINSNRISCV_SRL | OCINSNRISCV_IMMEDIATE)
#define OCINSNRISCV_SRLW               (OCINSNRISCV_SRL | OCINSN_32BIT)
#define OCINSNRISCV_SRLIW              (OCINSNRISCV_SRLI | OCINSN_32BIT)

#define OCINSNRISCV_XNORI              (OCINSNRISCV_XNOR | OCINSNRISCV_IMMEDIATE)

#define OCINSNRISCV_XORI               (OCINSNRISCV_XOR | OCINSNRISCV_IMMEDIATE)

#define OCINSNRISCV_SEXTB              (OCINSNRISCV_SEXT | OCINSN_8BIT)
#define OCINSNRISCV_SEXTH              (OCINSNRISCV_SEXT | OCINSN_16BIT)
#define OCINSNRISCV_SEXTW              (OCINSNRISCV_SEXT | OCINSN_32BIT)

#define OCINSNRISCV_ZEXTB              (OCINSNRISCV_ZEXT | OCINSN_8BIT)
#define OCINSNRISCV_ZEXTH              (OCINSNRISCV_ZEXT | OCINSN_16BIT)
#define OCINSNRISCV_ZEXTW              (OCINSNRISCV_ZEXT | OCINSN_32BIT)

#define OCINSNRISCV_JAL                (OCINSNRISCV_Jxx | OCINSNRISCV_LINK)
#define OCINSNRISCV_JR                 (OCINSNRISCV_Jxx | OCINSNRISCV_REGISTER)
#define OCINSNRISCV_JALR               (OCINSNRISCV_JAL | OCINSNRISCV_REGISTER)

#define OCINSNRISCV_BEQ                (OCINSNRISCV_Bxx | OCINSNRISCV_EQ)
#define OCINSNRISCV_BGE                (OCINSNRISCV_Bxx | OCINSNRISCV_GE)
#define OCINSNRISCV_BGT                (OCINSNRISCV_Bxx | OCINSNRISCV_GT)
#define OCINSNRISCV_BLE                (OCINSNRISCV_Bxx | OCINSNRISCV_LE)
#define OCINSNRISCV_BLT                (OCINSNRISCV_Bxx | OCINSNRISCV_LT)
#define OCINSNRISCV_BNE                (OCINSNRISCV_Bxx | OCINSNRISCV_NE)
#define OCINSNRISCV_BEQZ               (OCINSNRISCV_Bxx | OCINSNRISCV_EQZ)
#define OCINSNRISCV_BGEZ               (OCINSNRISCV_Bxx | OCINSNRISCV_GEZ)
#define OCINSNRISCV_BGTZ               (OCINSNRISCV_Bxx | OCINSNRISCV_GTZ)
#define OCINSNRISCV_BLEZ               (OCINSNRISCV_Bxx | OCINSNRISCV_LEZ)
#define OCINSNRISCV_BLTZ               (OCINSNRISCV_Bxx | OCINSNRISCV_LTZ)
#define OCINSNRISCV_BNEZ               (OCINSNRISCV_Bxx | OCINSNRISCV_NEZ)
#define OCINSNRISCV_BGEU               (OCINSNRISCV_BGE | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_BGTU               (OCINSNRISCV_BGT | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_BLEU               (OCINSNRISCV_BLE | OCINSNRISCV_UNSIGNED)
#define OCINSNRISCV_BLTU               (OCINSNRISCV_BLT | OCINSNRISCV_UNSIGNED)

#define OCREGRISCV_FP                  ((0x01))
#define OCREGRISCV_GP                  ((0x02))
#define OCREGRISCV_RA                  ((0x03))
#define OCREGRISCV_SP                  ((0x04))
#define OCREGRISCV_TP                  ((0x05))

#define OCREGRISCV_A0                  ((0x10))
#define OCREGRISCV_A1                  ((0x11))
#define OCREGRISCV_A2                  ((0x12))
#define OCREGRISCV_A3                  ((0x13))
#define OCREGRISCV_A4                  ((0x14))
#define OCREGRISCV_A5                  ((0x15))
#define OCREGRISCV_A6                  ((0x16))
#define OCREGRISCV_A7                  ((0x17))

#define OCREGRISCV_S0                  (OCREGRISCV_FP)
#define OCREGRISCV_S1                  ((0x20))
#define OCREGRISCV_S2                  ((0x22))
#define OCREGRISCV_S3                  ((0x23))
#define OCREGRISCV_S4                  ((0x24))
#define OCREGRISCV_S5                  ((0x25))
#define OCREGRISCV_S6                  ((0x26))
#define OCREGRISCV_S7                  ((0x27))
#define OCREGRISCV_S8                  ((0x28))
#define OCREGRISCV_S9                  ((0x29))
#define OCREGRISCV_S10                 ((0x2a))
#define OCREGRISCV_S11                 ((0x2b))

#define OCREGRISCV_T0                  ((0x30))
#define OCREGRISCV_T1                  ((0x31))
#define OCREGRISCV_T2                  ((0x32))
#define OCREGRISCV_T3                  ((0x33))
#define OCREGRISCV_T4                  ((0x34))
#define OCREGRISCV_T5                  ((0x35))
#define OCREGRISCV_T6                  ((0x36))

#define OCREGRISCV_X1                  (OCREGRISCV_RA)
#define OCREGRISCV_X2                  (OCREGRISCV_SP)
#define OCREGRISCV_X3                  (OCREGRISCV_GP)
#define OCREGRISCV_X4                  (OCREGRISCV_TP)
#define OCREGRISCV_X5                  (OCREGRISCV_T0)
#define OCREGRISCV_X6                  (OCREGRISCV_T1)
#define OCREGRISCV_X7                  (OCREGRISCV_T2)
#define OCREGRISCV_X8                  (OCREGRISCV_S0)
#define OCREGRISCV_X9                  (OCREGRISCV_S1)
#define OCREGRISCV_X10                 (OCREGRISCV_A0)
#define OCREGRISCV_X11                 (OCREGRISCV_A1)
#define OCREGRISCV_X12                 (OCREGRISCV_A2)
#define OCREGRISCV_X13                 (OCREGRISCV_A3)
#define OCREGRISCV_X14                 (OCREGRISCV_A4)
#define OCREGRISCV_X15                 (OCREGRISCV_A5)
#define OCREGRISCV_X16                 (OCREGRISCV_A6)
#define OCREGRISCV_X17                 (OCREGRISCV_A7)
#define OCREGRISCV_X18                 (OCREGRISCV_S2)
#define OCREGRISCV_X19                 (OCREGRISCV_S3)
#define OCREGRISCV_X20                 (OCREGRISCV_S4)
#define OCREGRISCV_X21                 (OCREGRISCV_S5)
#define OCREGRISCV_X22                 (OCREGRISCV_S6)
#define OCREGRISCV_X23                 (OCREGRISCV_S7)
#define OCREGRISCV_X24                 (OCREGRISCV_S8)
#define OCREGRISCV_X25                 (OCREGRISCV_S9)
#define OCREGRISCV_X26                 (OCREGRISCV_S10)
#define OCREGRISCV_X27                 (OCREGRISCV_S11)
#define OCREGRISCV_X28                 (OCREGRISCV_T3)
#define OCREGRISCV_X29                 (OCREGRISCV_T4)
#define OCREGRISCV_X30                 (OCREGRISCV_T5)
#define OCREGRISCV_X31                 (OCREGRISCV_T6)

#endif

